# Generated by Django 4.2.4 on 2023-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('year_of_publication', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('image_URL_S', models.CharField(max_length=50)),
                ('image_URL_M', models.CharField(max_length=50)),
                ('image_URL_L', models.CharField(max_length=50)),
            ],
        ),
    ]
