# Generated by Django 4.2.4 on 2023-08-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
